# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='', max_length=2),
        ),
    ]
