# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180311_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributions', models.FloatField()),
                ('losses', models.FloatField()),
                ('description', models.FloatField()),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
        ),
    ]
