# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_detailedinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedinformation',
            name='description',
            field=models.TextField(),
        ),
    ]
